/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josue
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastroDeVendas = new javax.swing.JButton();
        btnCadastroDeProdutos = new javax.swing.JButton();
        btnConsultaDeVendas = new javax.swing.JButton();
        btnConsultaDeProdutos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCadastroDeVendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastroDeVendas.setText("Cadastro de vendas");
        btnCadastroDeVendas.setToolTipText("Cadastro de vendas\n");
        btnCadastroDeVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroDeVendasActionPerformed(evt);
            }
        });

        btnCadastroDeProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastroDeProdutos.setText("Cadastro de produtos");
        btnCadastroDeProdutos.setToolTipText("Cadastro de produtos");
        btnCadastroDeProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroDeProdutosActionPerformed(evt);
            }
        });

        btnConsultaDeVendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConsultaDeVendas.setText("Consulta de vendas");
        btnConsultaDeVendas.setToolTipText("Consulta de vendas");
        btnConsultaDeVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaDeVendasActionPerformed(evt);
            }
        });

        btnConsultaDeProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConsultaDeProdutos.setText("Consulta de produtos");
        btnConsultaDeProdutos.setToolTipText("Consulta de produtos");
        btnConsultaDeProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaDeProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCadastroDeProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastroDeVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultaDeVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultaDeProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnCadastroDeVendas)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroDeProdutos)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaDeVendas)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaDeProdutos)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroDeVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroDeVendasActionPerformed
        // TODO add your handling code here:
        
        CadastroDeVendas telaVendas = new CadastroDeVendas();
        
        telaVendas.setVisible(true);
    }//GEN-LAST:event_btnCadastroDeVendasActionPerformed

    private void btnCadastroDeProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroDeProdutosActionPerformed
        // TODO add your handling code here:
        
        CadastroDeProdutos telaProdutos = new CadastroDeProdutos();
        
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_btnCadastroDeProdutosActionPerformed

    private void btnConsultaDeVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaDeVendasActionPerformed
        // TODO add your handling code here:
        
        ConsultaDeVendas telaConsultaVendas = new ConsultaDeVendas();
        
        telaConsultaVendas.setVisible(true);
    }//GEN-LAST:event_btnConsultaDeVendasActionPerformed

    private void btnConsultaDeProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaDeProdutosActionPerformed
        // TODO add your handling code here:
        
        ConsultaDeProdutos telaConsultaProdutos = new ConsultaDeProdutos();
        
        telaConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_btnConsultaDeProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroDeProdutos;
    private javax.swing.JButton btnCadastroDeVendas;
    private javax.swing.JButton btnConsultaDeProdutos;
    private javax.swing.JButton btnConsultaDeVendas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
